# AUTO-GENERATED by scripts/sync_client.py — DO NOT EDIT
# Source of truth: the flopscope core library (src/flopscope/)
# Regenerate: uv run scripts/sync_client.py
"""Server-only public names snapshot for the client."""

SERVER_ONLY: frozenset[str] = frozenset(
    {
        "FlopscopeArray",
        "PathInfo",
        "StepInfo",
        "SymmetricTensor",
        "budget_reset",
        "clear_einsum_cache",
        "einsum_cache_info",
        "namespace",
    }
)
